### ISSUE TITLE
Page on the site where all the clips are immediately visible

### ISSUE THREAD

**Issue by CosMarm** [selenearchive/selenearchive.github.io#11]
Ideally it would be essentially identical to the original reddit post. aside from all the text at the start and end

Seems like a nice choice if somebody's say, searching for a specific clip name or something (as they'll be able to ctrl+F)

**Comment by awth13** [comment]
Do we need topic headers for this one or is it going to be just a singular list of clips?

**Comment by CosMarm** [comment]
thinking topic headers without descriptions (such as what weight is and all that; keep stuff like "these help with conflations regarding size")

**Comment by awth13** [comment]
I am unsure if this issue is closed by #17. Right now, users have to manually open all topic "drawers" before they can Ctrl+F. Is this OK?

**Comment by CosMarm** [comment]
It's good enough, by all means 😅
Perfect compromise between convenience for the maintainers and the users, and also generally reduces clutter
